# Generated by Django 4.1.3 on 2022-12-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='files')),
            ],
        ),
        migrations.DeleteModel(
            name='UploadDetails',
        ),
    ]
