# Generated by Django 4.1.3 on 2022-12-20 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo_app', '0002_uploadfile_delete_uploaddetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_code', models.CharField(max_length=20)),
                ('agency_type', models.CharField(max_length=30)),
                ('agency_name', models.CharField(max_length=200)),
                ('agency_description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('lat', models.CharField(max_length=50)),
                ('lng', models.CharField(max_length=50)),
                ('cost', models.IntegerField()),
                ('timespan', models.IntegerField()),
                ('project_id', models.CharField(max_length=20)),
                ('goal', models.CharField(max_length=200)),
                ('proposal_date', models.FloatField()),
                ('executing_agency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geo_app.agency')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('lat', models.CharField(max_length=50)),
                ('lng', models.CharField(max_length=50)),
                ('cost', models.IntegerField()),
                ('timespan', models.IntegerField()),
                ('project_id', models.CharField(max_length=20)),
                ('goal', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('completion_date', models.DateField()),
                ('actual_cost', models.FloatField()),
                ('executing_agency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geo_app.agency')),
            ],
        ),
        migrations.CreateModel(
            name='Components',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=20)),
                ('component_id', models.CharField(max_length=30)),
                ('component_type', models.CharField(max_length=50)),
                ('executing_agency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geo_app.agency')),
            ],
        ),
    ]
