# Generated by Django 4.1.3 on 2022-12-20 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo_app', '0003_agency_proposal_projects_components'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='name',
            new_name='project_name',
        ),
    ]
