# Generated by Django 4.1.3 on 2022-12-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_app', '0004_rename_name_projects_project_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constraints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('max_limit', models.IntegerField()),
                ('constraint_type', models.CharField(max_length=80)),
            ],
        ),
    ]
