# Generated by Django 4.1.3 on 2022-12-20 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo_app', '0005_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constraints',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo_app.agency'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='proposal_date',
            field=models.DateField(),
        ),
    ]
