# Generated by Django 4.1.3 on 2022-12-20 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_app', '0006_alter_constraints_code_alter_proposal_proposal_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='completion_date',
        ),
        migrations.AddField(
            model_name='projects',
            name='completion',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
