# Generated by Django 4.1.3 on 2022-12-20 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo_app', '0007_remove_projects_completion_date_projects_completion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='components',
            name='project_id',
        ),
        migrations.AddField(
            model_name='components',
            name='budget_ratio',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='components',
            name='depends_on',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='components',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo_app.projects'),
        ),
        migrations.AddField(
            model_name='components',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo_app.proposal'),
        ),
    ]
