# Generated by Django 4.1.3 on 2022-12-20 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo_app', '0008_remove_components_project_id_components_budget_ratio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='components',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='geo_app.projects'),
        ),
        migrations.AlterField(
            model_name='components',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='geo_app.proposal'),
        ),
    ]
