# Generated by Django 4.1.3 on 2022-12-20 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_app', '0009_alter_components_project_alter_components_proposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='components',
            name='is_project',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='components',
            name='project',
            field=models.CharField(default='hello', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='components',
            name='proposal',
            field=models.CharField(default='hello', max_length=20),
            preserve_default=False,
        ),
    ]
