# Generated by Django 4.1.3 on 2022-12-20 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo_app', '0010_components_is_project_alter_components_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='components',
            name='executing_agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo_app.agency'),
        ),
    ]
