# Generated by Django 4.1.3 on 2022-12-20 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo_app', '0011_alter_components_executing_agency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='components',
            name='depends_on',
        ),
    ]
