# Generated by Django 4.1.3 on 2022-12-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_app', '0012_remove_components_depends_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='components',
            name='proposal',
        ),
        migrations.AddField(
            model_name='components',
            name='depends_on',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
