# Generated by Django 4.1.3 on 2022-12-20 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_app', '0013_remove_components_proposal_components_depends_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
