# Generated by Django 4.1.3 on 2022-12-20 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_app', '0015_proposal_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
