# Generated by Django 4.1.3 on 2022-12-20 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_app', '0016_issue_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='hold',
            field=models.BooleanField(default=True),
        ),
    ]
