# Generated by Django 4.1.3 on 2022-12-21 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo_app', '0018_agency_location_limit_agency_max_running_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='issue_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='issue',
            name='details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo_app.projects'),
        ),
    ]
