# Generated by Django 4.1.3 on 2022-12-21 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo_app', '0019_projects_issue_count_alter_issue_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locations',
            name='agency',
        ),
    ]
