# Generated by Django 4.1.3 on 2022-12-21 04:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('geo_app', '0020_remove_locations_agency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locations',
            old_name='count',
            new_name='max_count',
        ),
        migrations.AddField(
            model_name='locations',
            name='time',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='constraints',
            name='code',
            field=models.CharField(max_length=20),
        ),
    ]
