# Generated by Django 4.1.3 on 2022-12-21 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_app', '0021_rename_count_locations_max_count_locations_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
