# Generated by Django 4.1.3 on 2022-12-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('System Admin', 'System Admin'), ('Executive Committee of the National Economic Council', 'Executive Committee of the National Economic Council'), ('Ministry of Planning', 'Ministry of Planning'), ('Executing Agency', 'Executing Agency')], max_length=100, null=True, verbose_name='User Role'),
        ),
    ]
